rudott_site:
    resource: "@RudottSiteBundle/Resources/config/routing.yml"
    prefix:   /

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

# KunstmaanMediaBundle
_imagine:
    resource: .
    type:     imagine

KunstmaanMediaBundle:
    resource: "@KunstmaanMediaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%

# KunstmaanAdminBundle
KunstmaanAdminBundle:
    resource: "@KunstmaanAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%

# KunstmaanNodeBundle
KunstmaanNodeBundle:
    resource: "@KunstmaanNodeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%

# KunstmaanPagePartBundle
KunstmaanPagePartBundle:
    resource: "@KunstmaanPagePartBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%

# KunstmaanFormBundle
#KunstmaanFormBundle:
#    resource: "@KunstmaanFormBundle/Resources/config/routing.yml"
#    prefix:   /{_locale}/
#    requirements:
#        _locale: %requiredlocales%
