rudott_site:
    resource: "@RudottSiteBundle/Resources/config/routing.yml"
    prefix:   /

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

kunstmaan:
    resource: kunstmaan-multi-language.yml
#    resource: kunstmaan-single-language.yml
