name: "Home page"
rows:
    - regions:
        - { name: "left_column", span: 4 }
        - { name: "middle_column", span: 4 }
        - { name: "right_column", span: 4 }
template: "RudottSiteBundle::Pages\\HomePage\\pagetemplate.html.twig"